### ISSUE TITLE
Option for toggling other flags absent

### ISSUE THREAD

**Issue by MacgyverJohnson** [jacopotediosi/GoogleDialerMod-Magisk#3]
Hi there @jacopotediosi ,
Totally loved your google dialer mod( non magisk version). I could enable call recording and silencing...as well as other hidden flags...but in magisk version I could not find a way to modify other flags...How to achieve that? I am interested in the magisk version  as it can survive ota and other upgrades.....

**Comment by jacopotediosi** [comment]
Hi @MacgyverJohnson,
The magisk version does exactly the same as the app. Both should survive to ota and other upgrades.
Unfortunately, I don't know how I could implement all the flags in the Magisk module. I don't think asking "yes / no" for each of the over 300 flags would be a good solution. Of course, ideas on this are welcome.

**Comment by jacopotediosi** [comment]
Hi!

Google Dialer Mod - Magisk is going deprecated.

Please use only the standalone APK version: https://github.com/jacopotediosi/GoogleDialerMod
The latest release should support any Android version, even Android> = 11

For this reason I am closing the issues in this repository, which later will be archived.

If you find bugs in the standalone version, please report them there: https://github.com/jacopotediosi/GoogleDialerMod/issues
