### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Durocks** [jacopotediosi/GoogleDialerMod-Magisk#4]
It's not working on my Pixel UI ROM OnePlus 7 Pro. The APK version works, but it has to be re-applied after rebooting the phone.

**Comment by jacopotediosi** [comment]
Hi!

Google Dialer Mod - Magisk is going deprecated.

Please use only the standalone APK version: https://github.com/jacopotediosi/GoogleDialerMod
The latest release should support any Android version, even Android> = 11

For this reason I am closing the issues in this repository, which later will be archived.

If you find bugs in the standalone version, please report them there: https://github.com/jacopotediosi/GoogleDialerMod/issues
