### ISSUE TITLE
file location

### ISSUE THREAD

**Issue by bittoe** [jacopotediosi/GoogleDialerMod-Magisk#5]
I am using the magisk module by itself -no APK, and it works great!
But is there a way to change the default save location for the recordings?
As it is now I have a folder shortcut on the home screen and then transfer the file to a "recordings" folder after the call.

Pixel 6 Pro
rooted Stock android 12

biTToe

**Comment by jacopotediosi** [comment]
Google Dialer Mod - Magisk is going deprecated.

Please use only the standalone APK version: https://github.com/jacopotediosi/GoogleDialerMod

Regarding your specific issue, I took it there: https://github.com/jacopotediosi/GoogleDialerMod/issues/41
