### ISSUE TITLE
Arrow 10

### ISSUE THREAD

**Issue by wita74** [jacopotediosi/GoogleDialerMod-Magisk#8]
Installed on anroid 10 arrow and that just did not make a recording error, everything worked on android 12 arrow, but the recording notification did not muffle

**Comment by wita74** [comment]
устройство Xiaomi redmi note 4x  4/64 mido

**Comment by jacopotediosi** [comment]
Hi!

Google Dialer Mod - Magisk is going deprecated.

Please use only the standalone APK version: https://github.com/jacopotediosi/GoogleDialerMod
The latest release should support any Android version, even Android> = 11

For this reason I am closing the issues in this repository, which later will be archived.

If you find bugs in the standalone version, please report them there: https://github.com/jacopotediosi/GoogleDialerMod/issues
